### ISSUE TITLE
There is some problem with CI and redis

### ISSUE THREAD

**Issue by vietvudanh** [vietvudanh/geo-redis#1]
Install from scratch, fine on local, however on CI get some problem, seems could be 2 sources:
1. redis-py is not install from `pip`
2. redis version on CI not support GEO?

This is the log: Cannot add and cannot get radius.

> # .F..F.....F
> ## FAIL: test_add_success (TestAdd.TestAdd)
> 
> Traceback (most recent call last):
>   File "/home/travis/build/vietvudanh/geo-redis/test/TestAdd.py", line 24, in test_add_success
>     self.assertTrue(self._geo_redis.add(self.KEY, lat, lon, name))
> # AssertionError: False is not true
> ## FAIL: test_get_all (TestGet.TestGet)
> 
> Traceback (most recent call last):
>   File "/home/travis/build/vietvudanh/geo-redis/test/TestGet.py", line 30, in test_get_all
>     self.assertEqual(len(all_data), len(self.test_data_added))
> # AssertionError: 0 != 4
> ## FAIL: test_get_by_radius_success (TestGetRadius.TestGetRadius)
> 
> Traceback (most recent call last):
>   File "/home/travis/build/vietvudanh/geo-redis/test/TestGetRadius.py", line 47, in test_get_by_radius_success
>     self.KEY, lat, lon, r, unit), list)
> AssertionError: None is not an instance of <type 'list'>
> -------------------- >> begin captured stdout << ---------------------
> unknown command 'GEORADIUS'
> ## --------------------- >> end captured stdout << ----------------------
> 
> Ran 11 tests in 0.052s

**Comment by vietvudanh** [comment]
The problem was Travis only support some environments, even though I have used the latest ([Trusty - Ubuntu1404](https://docs.travis-ci.com/user/trusty-ci-environment/)),
 Redis is still 3.0.6

> Redis version
> redis-server 3.0.6
